# coding=utf-8
# Copyright 2023 Google AI and The HuggingFace Inc. team. All rights reserved.
# Copyright 2024 EPFL and Apple Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""PyTorch ViViT model."""

import math
import warnings
from functools import partial
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.checkpoint as checkpoint
from torch.cuda.amp import autocast
from einops import rearrange
from transformers import VivitModel
# xFormers imports
try:
    from xformers.ops import memory_efficient_attention, unbind
    XFORMERS_AVAILABLE = True
except ImportError:
    print("xFormers not available")
    XFORMERS_AVAILABLE = False

XFORMERS_AVAILABLE = False

def pair(t):
    return t if isinstance(t, tuple) else (t, t)


def build_2d_sincos_posemb(h, w, embed_dim=1024, temperature=10000.):
    """Sine-cosine positional embeddings as used in MoCo-v3
    """
    grid_w = torch.arange(w, dtype=torch.float32)
    grid_h = torch.arange(h, dtype=torch.float32)
    grid_w, grid_h = torch.meshgrid(grid_w, grid_h, indexing='ij')
    assert embed_dim % 4 == 0, 'Embed dimension must be divisible by 4 for 2D sin-cos position embedding'
    pos_dim = embed_dim // 4
    omega = torch.arange(pos_dim, dtype=torch.float32) / pos_dim
    omega = 1. / (temperature ** omega)
    out_w = torch.einsum('m,d->md', [grid_w.flatten(), omega])
    out_h = torch.einsum('m,d->md', [grid_h.flatten(), omega])
    pos_emb = torch.cat([torch.sin(out_w), torch.cos(out_w), torch.sin(out_h), torch.cos(out_h)], dim=1)[None, :, :]
    pos_emb = rearrange(pos_emb, 'b (h w) d -> b h w d', h=h, w=w, d=embed_dim)
    return pos_emb


def build_3d_sincos_posemb(t, h, w, embed_dim=1024, temperature=10000.):
    """Sine-cosine positional embeddings for vivit tubelets
    """
    assert embed_dim % 6 == 0, 'Embed dimension must be divisible by 6 for 3D sin-cos position embedding'
    channels = int(embed_dim // 6 * 2)
    inv_freq = 1.0 / (temperature ** (torch.arange(0, channels, 2).float() / channels))

    pos_x = torch.arange(t, dtype=torch.float32)
    pos_y = torch.arange(h, dtype=torch.float32)
    pos_z = torch.arange(w, dtype=torch.float32)
    sin_inp_x = torch.einsum("i,j->ij", pos_x, inv_freq)
    sin_inp_y = torch.einsum("i,j->ij", pos_y, inv_freq)
    sin_inp_z = torch.einsum("i,j->ij", pos_z, inv_freq)

    emb_x = torch.flatten(torch.stack((sin_inp_x.sin(), sin_inp_x.cos()), dim=-1), -2, -1).unsqueeze(1).unsqueeze(1)
    emb_y = torch.flatten(torch.stack((sin_inp_y.sin(), sin_inp_y.cos()), dim=-1), -2, -1).unsqueeze(1)
    emb_z = torch.flatten(torch.stack((sin_inp_z.sin(), sin_inp_z.cos()), dim=-1), -2, -1)

    emb = torch.zeros((1, t, h, w, channels * 3), dtype=torch.float32)
    emb[:, :, :, :, : channels] = emb_x
    emb[:, :, :, :, channels : 2 * channels] = emb_y
    emb[:, :, :, :, 2 * channels :] = emb_z
    emb = rearrange(emb, 'b t h w d -> b (t h w) d', t=t, h=h, w=w, d=embed_dim)
    return emb


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)

    def extra_repr(self) -> str:
        return 'p={}'.format(self.drop_prob)


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        # commit this for the orignal BERT implement 
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = head_dim ** -0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads)

        if XFORMERS_AVAILABLE:
            q, k, v = unbind(qkv, 2) # Each is of shape B x N x num_heads x C // num_heads
            x = memory_efficient_attention(q, k, v)
            x = x.reshape([B, N, C])
        else:
            qkv = qkv.permute(2, 0, 3, 1, 4)
            q, k, v = qkv.unbind(0)   # make torchscript happy (cannot use tensor as tuple)

            attn = (q @ k.transpose(-2, -1)) * self.scale
            attn = attn.softmax(dim=-1)
            attn = self.attn_drop(attn)

            x = (attn @ v).transpose(1, 2).reshape(B, N, C)

        x = self.proj(x)
        x = self.proj_drop(x)
        return x


class CrossAttention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = head_dim ** -0.5

        self.q = nn.Linear(dim, dim, bias=qkv_bias)
        self.kv = nn.Linear(dim, dim * 2, bias=qkv_bias)

        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x, context):
        B, N, C = x.shape
        _, M, _ = context.shape

        q = self.q(x).reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)
        kv = self.kv(context).reshape(B, M, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        k, v = kv[0], kv[1]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, -1)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x


class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, drop=0., attn_drop=0., 
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.norm2 = norm_layer(dim)
        self.attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, attn_drop=attn_drop, proj_drop=drop)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

    def forward(self, x, **kwargs):
        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


class DecoderBlock(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, drop=0., attn_drop=0., 
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.self_attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, attn_drop=attn_drop, proj_drop=drop)
        self.cross_attn = CrossAttention(dim, num_heads=num_heads, qkv_bias=qkv_bias, attn_drop=attn_drop, proj_drop=drop)
        self.query_norm = norm_layer(dim)
        self.context_norm = norm_layer(dim)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

    def forward(self, x, context, **kwargs):
        x = x + self.drop_path(self.self_attn(self.norm1(x)))
        x = x + self.drop_path(self.cross_attn(self.query_norm(x), self.context_norm(context)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


class LayerNorm(nn.Module):
    r""" LayerNorm that supports two data formats: channels_last (default) or channels_first. 
    The ordering of the dimensions in the inputs. channels_last corresponds to inputs with 
    shape (batch_size, height, width, channels) while channels_first corresponds to inputs 
    with shape (batch_size, channels, height, width).

    From https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py
    """
    def __init__(self, normalized_shape, eps=1e-6, data_format="channels_last"):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(normalized_shape))
        self.bias = nn.Parameter(torch.zeros(normalized_shape))
        self.eps = eps
        self.data_format = data_format
        if self.data_format not in ["channels_last", "channels_first"]:
            raise NotImplementedError 
        self.normalized_shape = (normalized_shape, )
    
    def forward(self, x):
        if self.data_format == "channels_last":
            return F.layer_norm(x, self.normalized_shape, self.weight, self.bias, self.eps)
        elif self.data_format == "channels_first":
            u = x.mean(1, keepdim=True)
            s = (x - u).pow(2).mean(1, keepdim=True)
            x = (x - u) / torch.sqrt(s + self.eps)
            x = self.weight[:, None, None] * x + self.bias[:, None, None]
            return x

class ConvNeXtBlock(nn.Module):
    r""" ConvNeXt Block. There are two equivalent implementations:
    (1) DwConv -> LayerNorm (channels_first) -> 1x1 Conv -> GELU -> 1x1 Conv; all in (N, C, H, W)
    (2) DwConv -> Permute to (N, H, W, C); LayerNorm (channels_last) -> Linear -> GELU -> Linear; Permute back
    We use (2) as we find it slightly faster in PyTorch.

    From https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py
    
    Args:
        dim (int): Number of input channels.
        drop_path (float): Stochastic depth rate. Default: 0.0
        layer_scale_init_value (float): Init value for Layer Scale. Default: 1e-6.
    """
    def __init__(self, dim, drop_path=0., layer_scale_init_value=1e-6):
        super().__init__()
        self.dwconv = nn.Conv2d(dim, dim, kernel_size=7, padding=3, groups=dim) # depthwise conv
        self.norm = nn.LayerNorm(dim, eps=1e-6)
        self.pwconv1 = nn.Linear(dim, 4 * dim) # pointwise/1x1 convs, implemented with linear layers
        self.act = nn.GELU()
        self.pwconv2 = nn.Linear(4 * dim, dim)
        self.gamma = nn.Parameter(layer_scale_init_value * torch.ones((dim)), 
                                    requires_grad=True) if layer_scale_init_value > 0 else None
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()

    def forward(self, x):
        input = x
        x = self.dwconv(x)
        x = x.permute(0, 2, 3, 1) # (N, C, H, W) -> (N, H, W, C)
        x = self.norm(x)
        x = self.pwconv1(x)
        x = self.act(x)
        x = self.pwconv2(x)
        if self.gamma is not None:
            x = self.gamma * x
        x = x.permute(0, 3, 1, 2) # (N, H, W, C) -> (N, C, H, W)

        x = input + self.drop_path(x)
        return x
    

class VivitTubeletEmbeddings(nn.Module):
    """
    Construct Vivit Tubelet embeddings.

    This module turns a batch of videos of shape (batch_size, num_frames, num_channels, height, width) into a tensor of
    shape (batch_size, seq_len, hidden_size) to be consumed by a Transformer encoder.

    The seq_len (the number of patches) equals (number of frames // tubelet_size[0]) * (height // tubelet_size[1]) *
    (width // tubelet_size[2]).

    Args:
        in_channels: Number of input channels.
        num_frames: The number of frames in each video.
        tubelet_size: The size (resolution) of each tubelet.
        resolution: Image resolution.
        dim_tokens: Transformer dimension.
    """

    def __init__(self, in_channels: int = 3,
                 num_frames: int = 32, 
                 resolution: int = 224, 
                 tubelet_size = [2, 16, 16],
                 dim_tokens: int = 768
                 ):
        super().__init__()
        self.num_frames = num_frames
        self.image_size = resolution
        self.patch_size = tubelet_size
        self.num_patches = (
            (self.image_size // self.patch_size[2])
            * (self.image_size // self.patch_size[1])
            * (self.num_frames // self.patch_size[0])
        )
        self.embed_dim = dim_tokens

        self.projection = nn.Conv3d(
            in_channels, self.embed_dim, kernel_size=tubelet_size, stride=tubelet_size
        ) # TODO: initialize conv3d weight

    def forward(self, pixel_values, interpolate_pos_encoding: bool = False):
        batch_size, num_channels, num_frames, height, width = pixel_values.shape
        if not interpolate_pos_encoding and (height != self.image_size or width != self.image_size):
            raise ValueError(
                f"Image image size ({height}*{width}) doesn't match model"
                f" ({self.image_size[0]}*{self.image_size[1]})."
            )

        # permute to (batch_size, num_channels, num_frames, height, width)

        x = self.projection(pixel_values)

        # flattens time and space dimensions, transposes to (out_batch_size, flat_tokens, out_num_channels)
        x = x.flatten(2).transpose(1, 2)
        return x
    

class VivitEmbeddings(nn.Module):
    """
    Vivit Embeddings.

    Creates embeddings from a video using VivitTubeletEmbeddings, adds positional embeddings.

    Args:
        in_channels: Number of input channels.
        num_frames: The number of frames in each video.
        tubelet_size: The size (resolution) of each tubelet.
        resolution: Image resolution.
        dim_tokens: Transformer dimension.
        learnable_pos_emb: If True, learn positional embedding.
        drop_rate: Dropout rate.
        sincos_pos_emb: If True, use sine-cosine positional embedding.
    """

    def __init__(self, in_channels: int = 3,
                 num_frames: int = 32, 
                 resolution: int = 224, 
                 tubelet_size = [2, 16, 16],
                 dim_tokens: int = 768,
                 learnable_pos_emb: bool = False, 
                 drop_rate: float = 0.0,
                 sincos_pos_emb: bool = True
                 ):
        super().__init__()

        self.patch_embeddings = VivitTubeletEmbeddings(in_channels=in_channels, 
                                                       num_frames=num_frames, 
                                                       resolution=resolution, 
                                                       tubelet_size=tubelet_size, 
                                                       dim_tokens=dim_tokens)

        # TODO: i want to use 3d fixed pos enc
        # )

        N_T = num_frames // tubelet_size[0]
        N_H = resolution // tubelet_size[1]
        N_W = resolution // tubelet_size[2]
        
        if sincos_pos_emb:
            self.position_embeddings = build_3d_sincos_posemb(t=N_T, h=N_H, w=N_W, embed_dim=dim_tokens)
            #                                                                     t_size=tubelet_size[0])).float().unsqueeze(0)
            self.position_embeddings = nn.Parameter(self.position_embeddings, requires_grad=learnable_pos_emb)
        else:
            self.position_embeddings = nn.Parameter(torch.zeros(1, N_T * N_H * N_W, dim_tokens))
            trunc_normal_(self.position_embeddings, std=0.02)

        self.dropout = nn.Dropout(drop_rate)

    def interpolate_pos_encoding(self, embeddings, height, width):
        """
        This method allows to interpolate the pre-trained position encodings, to be able to use the model on higher
        resolution images.

        Source:
        https://github.com/facebookresearch/dino/blob/de9ee3df6cf39fac952ab558447af1fa1365362a/vision_transformer.py#L174
        """

        num_patches = embeddings.shape[1]
        num_positions = self.position_embeddings.shape[1]
        if num_patches == num_positions and height == width:
            return self.position_embeddings
        patch_pos_embed = self.position_embeddings  # [:, 1:]
        dim = embeddings.shape[-1]
        h0 = height // self.config.patch_size
        w0 = width // self.config.patch_size
        # we add a small number to avoid floating point error in the interpolation
        # see discussion at https://github.com/facebookresearch/dino/issues/8
        h0, w0 = h0 + 0.1, w0 + 0.1
        patch_pos_embed = patch_pos_embed.reshape(1, int(math.sqrt(num_positions)), int(math.sqrt(num_positions)), dim)
        patch_pos_embed = patch_pos_embed.permute(0, 3, 1, 2)
        patch_pos_embed = nn.functional.interpolate(
            patch_pos_embed,
            scale_factor=(h0 / math.sqrt(num_positions), w0 / math.sqrt(num_positions)),
            mode="bicubic",
            align_corners=False,
        )
        patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1).view(1, -1, dim)
        return patch_pos_embed

    def forward(self, pixel_values, interpolate_pos_encoding: bool = False):
        batch_size, num_channels, num_frames, height, width = pixel_values.shape
        embeddings = self.patch_embeddings(pixel_values, interpolate_pos_encoding=interpolate_pos_encoding)


        # add positional encoding to each token
        if interpolate_pos_encoding:
            embeddings = embeddings + self.interpolate_pos_encoding(embeddings, height, width)
        else:
            embeddings = embeddings + self.position_embeddings

        embeddings = self.dropout(embeddings)

        return embeddings


class VivitEncoder(nn.Module):
    """Transformer to map videos to latent features.
    
    Args:
        in_channels: Number of input channels.
        num_frames: The number of frames in each video.
        tubelet_size: The size (resolution) of each tubelet.
        resolution: Image resolution.
        dim_tokens: Transformer dimension.
        depth: Number of transformer layers.
        num_heads: Number of attention heads.
        mlp_ratio: MLP ratio.
        qkv_bias: If True, add bias to the qkv projection.
        drop_rate: Dropout rate.
        attn_drop_rate: Attention dropout rate.
        drop_path_rate: Stochastic depth rate.
        norm_layer: Normalization layer.
        sincos_pos_emb: If True, use sine-cosine positional embedding.
        learnable_pos_emb: If True, learn positional embedding.
        patch_proj: If True, project image patches to tokens.
          Consider disabling when encoding feature maps.
        post_mlp: If True, add MLP after transformer.
          See https://arxiv.org/abs/2110.04627.
        ckpt_path: Path to checkpoint to load.
    """
    def __init__(self, *, 
                 in_channels: int = 3, 
                 num_frames: int = 32,
                 tubelet_size = [2, 16, 16],
                 resolution: int = 224,
                 dim_tokens: int = 768,
                 depth: int = 12,
                 num_heads: int = 12,
                 mlp_ratio: float = 4.0,
                 qkv_bias: bool = True,
                 drop_rate: float = 0.0,
                 attn_drop_rate: float = 0.0,
                 drop_path_rate: float = 0.0,
                 norm_layer: nn.Module = partial(nn.LayerNorm, eps=1e-6),
                 sincos_pos_emb: bool = True, 
                 learnable_pos_emb: bool = False, 
                 patch_proj: bool = True,
                 post_mlp: bool = False,
                 ckpt_path: Optional[str] = None,
                 **ignore_kwargs):
        super().__init__()
        self.in_channels = in_channels
        self.P_T, self.P_H, self.P_W = tubelet_size
        self.H, self.W = pair(resolution)
        self.dim_tokens = dim_tokens
        self.patch_proj = patch_proj

        assert (self.H % self.P_H == 0) and (self.W % self.P_W == 0), f'Image sizes {self.H}x{self.W} must be divisible by patch sizes {self.P_H}x{self.P_W}'
        assert (num_frames % self.P_T == 0), f'Video frames {num_frames} must be divisible by tubelet time size {self.P_T}'

        N_H = self.H // self.P_H
        N_W = self.W // self.P_W
        
        self.embeddings = VivitEmbeddings(in_channels=in_channels, 
                                          num_frames=num_frames, 
                                          resolution=resolution, 
                                          tubelet_size=tubelet_size, 
                                          dim_tokens=dim_tokens, 
                                          learnable_pos_emb=learnable_pos_emb, 
                                          drop_rate=drop_rate,
                                          sincos_pos_emb=sincos_pos_emb)

        # Transformer blocks
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks = nn.Sequential(*[
            Block(dim=dim_tokens, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias,
                  drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)
        ])
        self.depth = depth

        if post_mlp:
            self.norm_mlp = norm_layer(dim_tokens)
            self.post_mlp = Mlp(dim_tokens, int(mlp_ratio*dim_tokens), act_layer=nn.Tanh)
        
        self.apply(self._init_weights)
        for name, m in self.named_modules():
            if isinstance(m, nn.Linear):
                if 'qkv' in name:
                    # treat the weights of Q, K, V separately
                    val = math.sqrt(6. / float(m.weight.shape[0] // 3 + m.weight.shape[1]))
                    nn.init.uniform_(m.weight, -val, val)
                elif 'kv' in name:
                    # treat the weights of K, V separately
                    val = math.sqrt(6. / float(m.weight.shape[0] // 2 + m.weight.shape[1]))
                    nn.init.uniform_(m.weight, -val, val)

            if isinstance(m, nn.Conv2d):
                if '.proj' in name:
                    # From MAE, initialize projection like nn.Linear (instead of nn.Conv2d)
                    w = m.weight.data
                    nn.init.xavier_uniform_(w.view([w.shape[0], -1]))
                    # TODO: this branch may never exec. Check if this is a bug
                    pass



        if ckpt_path is not None:
            print(f'Loading checkpoint from {ckpt_path}')
            pass

            ckpt = torch.load(ckpt_path)
            ckpt['model']['pos_emb'] = rearrange(ckpt['model']['pos_embed'][:,1:], 'b (nh nw) d -> b d nh nw', nh=N_H, nw=N_W)
            ckpt['model']['proj.weight'] = ckpt['model']['patch_embed.proj.weight']
            ckpt['model']['proj.bias'] = ckpt['model']['patch_embed.proj.bias']
            msg = self.load_state_dict(ckpt['model'], strict=False)
            print(msg)

    def _init_weights(self, m: nn.Module) -> None:
        """Weight initialization"""
        if isinstance(m, (nn.Linear, nn.Conv3d, nn.Conv2d)):
            nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def get_num_layers(self) -> int:
        """Get number of transformer layers."""
        return len(self.blocks)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """ViViT encoder forward pass.
        
        Args:
            x: Input tensor of shape [B, C, T, H, W] or 
              [B, C, T, N_H, N_W] (patch projection disabled).
        Returns:
            Output tensor of shape [B, dim_tokens, N_T, N_H, N_W].
        """
        if self.patch_proj:
            B, C, T, H, W = x.shape
            assert (T % self.P_T == 0) and (H % self.P_H == 0) and (W % self.P_W == 0), f'Video sizes {T}x{H}x{W} must be divisible by tubelet sizes {self.P_T}x{self.P_H}x{self.P_W}'
            N_T, N_H, N_W = T // self.P_T , H // self.P_H, W // self.P_W # Number of patches in time, height and width
        else:
            B, N_T, C, N_H, N_W = x.shape
            pass


        # patches -> tubelet emb. [B C N H W] -> [B seq_len D]
        x = self.embeddings(x)

        # Transformer forward pass
        x = self.blocks(x)

        if hasattr(self, 'post_mlp'):
            with autocast(enabled = False):
                x = x.float() + self.post_mlp(self.norm_mlp(x.float()))

        # Reshape into 3D grid
        x = rearrange(x, 'b (nt nh nw) d -> b d nt nh nw', nt=N_T, nh=N_H, nw=N_W)

        return x


class VivitDecoder(nn.Module):
    """Transformer to map latent features back to images / feature maps.
    
    Args:
        out_channels: Number of output channels.
        num_frames: The number of frames in each video.
        tubelet_size: The size (resolution) of each tubelet.
        resolution: Image resolution.
        dim_tokens: Transformer dimension.
        depth: Number of transformer layers.
        num_heads: Number of attention heads.
        mlp_ratio: MLP ratio.
        qkv_bias: If True, add bias to the qkv projection.
        drop_rate: Dropout rate.
        attn_drop_rate: Attention dropout rate.
        drop_path_rate: Stochastic depth rate.
        norm_layer: Normalization layer.
        sincos_pos_emb: If True, use sine-cosine positional embedding.
        learnable_pos_emb: If True, learn positional embedding.
        patch_proj: If True, reproject tokens back to images.
          Consider disabling when encoding feature maps.
        post_mlp: If True, add MLP before transformer.
          See https://arxiv.org/abs/2110.04627.
        out_conv: If True, add two ConvNeXt blocks after transformer
          to deal with patch checkerboard artifacts.
    """
    def __init__(self, *, 
                 out_channels: int = 3, 
                 num_frames: int = 32,
                 tubelet_size=[2, 16, 16],
                 resolution: int = 256,
                 dim_tokens: int = 768,
                 depth: int = 12,
                 num_heads: int = 12,
                 mlp_ratio: float = 4.0,
                 qkv_bias: bool = True,
                 drop_rate: float = 0.0,
                 attn_drop_rate: float = 0.0,
                 drop_path_rate: float = 0.0,
                 norm_layer: nn.Module = partial(nn.LayerNorm, eps=1e-6),
                 sincos_pos_emb: bool = True, 
                 learnable_pos_emb: bool = False,
                 patch_proj: bool = True,
                 post_mlp: bool = False,
                 out_conv: bool = False,
                 **ignore_kwargs):
        super().__init__()

        self.out_channels = out_channels
        self.P_T, self.P_H, self.P_W = tubelet_size
        self.H, self.W = pair(resolution)
        self.dim_tokens = dim_tokens
        self.patch_proj = patch_proj

        assert (self.H % self.P_H == 0) and (self.W % self.P_W == 0), f'Image sizes {self.H}x{self.W} must be divisible by patch sizes {self.P_H}x{self.P_W}'
        assert (num_frames % self.P_T == 0), f'Video frames {num_frames} must be divisible by tubelet time size {self.P_T}'

        N_H = self.H // self.P_H
        N_W = self.W // self.P_W
        N_T = num_frames // self.P_T

        if sincos_pos_emb:
            self.position_embeddings = build_3d_sincos_posemb(t=N_T, h=N_H, w=N_W, embed_dim=dim_tokens)
            #                                                                     t_size=tubelet_size[0])).float().unsqueeze(0)
            self.position_embeddings = nn.Parameter(self.position_embeddings, requires_grad=learnable_pos_emb)
        else:
            self.position_embeddings = nn.Parameter(torch.zeros(1, N_T * N_H * N_W, dim_tokens))
            trunc_normal_(self.position_embeddings, std=0.02)

        # Transformer blocks
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks = nn.Sequential(*[
            Block(dim=dim_tokens, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias,
                  drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)
        ])

        # Tokens -> image output projection
        if post_mlp:
            self.norm_mlp = norm_layer(dim_tokens)
            self.post_mlp = Mlp(dim_tokens, int(mlp_ratio*dim_tokens), act_layer=nn.Tanh)
        if patch_proj:
            self.out_proj = nn.Linear(dim_tokens, self.out_channels * self.P_T * self.P_H * self.P_W)
        else:
            self.out_proj = nn.Linear(dim_tokens, self.out_channels)
        if out_conv:
            self.out_conv = nn.Sequential(ConvNeXtBlock(dim=self.out_channels), ConvNeXtBlock(dim=self.out_channels))
        
        self.apply(self._init_weights)
        for name, m in self.named_modules():
            if isinstance(m, nn.Linear):
                if 'qkv' in name:
                    # treat the weights of Q, K, V separately
                    val = math.sqrt(6. / float(m.weight.shape[0] // 3 + m.weight.shape[1]))
                    nn.init.uniform_(m.weight, -val, val)
                elif 'kv' in name:
                    # treat the weights of K, V separately
                    val = math.sqrt(6. / float(m.weight.shape[0] // 2 + m.weight.shape[1]))
                    nn.init.uniform_(m.weight, -val, val)

            if isinstance(m, nn.Conv2d):
                if '.proj' in name:
                    # From MAE, initialize projection like nn.Linear (instead of nn.Conv2d)
                    w = m.weight.data
                    nn.init.xavier_uniform_(w.view([w.shape[0], -1]))
                    # TODO: this branch may never exec. Check if this is a bug
                    pass


    def _init_weights(self, m: nn.Module) -> None:
        """Weight initialization"""
        if isinstance(m, (nn.Linear, nn.Conv3d, nn.Conv2d)):
            nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def get_num_layers(self) -> int:
        """Get number of transformer layers."""
        return len(self.blocks)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """ViviT decoder forward pass.
        Args:
            x: Input tensor of shape [B, dim_tokens, N_T, N_H, N_W].

        Returns:
            Output tensor of shape [B, C, T, H, W] or 
              [B, C, N_T, N_H, N_W] (patch projection disabled).
        """
        B, D, N_T, N_H, N_W = x.shape

        # Reshape into 1D
        x = rearrange(x, 'b d nt nh nw -> b (nt nh nw) d')

        """ # now we do not interpolate positional embedding. Maybe we need it for higher resolution videos
        if self.position_embeddings is not None:
            # Create positional embedding
            x_pos_emb = F.interpolate(self.position_embeddings, size=(N_H, N_W), mode='bicubic', align_corners=False)
            x_pos_emb = rearrange(x_pos_emb, 'b d nh nw -> b (nh nw) d')
            # Add positional embeddings to patches
            x = x + x_pos_emb
        """
        x = x + self.position_embeddings

        # Transformer forward pass
        x = self.blocks(x)

        # Project each token to (C * P_H * P_W)
        if hasattr(self, 'post_mlp'):
            with autocast(enabled = False): # layer_norm is not stable for fp16.
                x = x.float() + self.post_mlp(self.norm_mlp(x.float()))
                if x.isnan().any():
                    pass


        x = self.out_proj(x)

        # Reshape sequence of patches into video or output features
        pt, ph, pw = (self.P_T, self.P_H, self.P_W) if self.patch_proj else (1, 1, 1)
        x = rearrange(
            x, 'b (nt nh nw) (c pt ph pw) -> b c (nt pt) (nh ph) (nw pw)',
            nt=N_T, nh=N_H, nw=N_W, pt=pt, ph=ph, pw=pw, c=self.out_channels
        )

        # Optional conv layers to reduce patch artifacts
        if hasattr(self, 'out_conv'):
            x = self.out_conv(x)

        return x


# Encoder presets

def vivit_s_enc(in_channels, 
              num_frames, 
              tubelet_size,
              resolution, 
              drop_rate=0.0,
              attn_drop_rate=0.0,
              drop_path_rate=0.0,
              norm_layer=partial(nn.LayerNorm, eps=1e-6),
              sincos_pos_emb=True,
              learnable_pos_emb=False,
              patch_proj=True,
              post_mlp=False):
    model = VivitEncoder(
        in_channels=in_channels, 
        num_frames=num_frames,
        tubelet_size=tubelet_size,
        resolution=resolution,
        dim_tokens=512,
        depth=8,
        num_heads=8,
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=drop_rate,
        attn_drop_rate=attn_drop_rate,
        drop_path_rate=drop_path_rate,
        norm_layer=norm_layer,
        sincos_pos_emb=sincos_pos_emb,
        learnable_pos_emb=learnable_pos_emb,
        patch_proj=patch_proj,
        post_mlp=post_mlp,
    )
    return model

def vivit_b_enc(in_channels, 
              num_frames,
              tubelet_size, 
              resolution, 
              drop_rate=0.0,
              attn_drop_rate=0.0,
              drop_path_rate=0.0,
              norm_layer=partial(nn.LayerNorm, eps=1e-6),
              sincos_pos_emb=True,
              learnable_pos_emb=False,
              patch_proj=True,
              post_mlp=False,
              ckpt_path=None):
    model = VivitEncoder(
        in_channels=in_channels, 
        num_frames=num_frames,
        tubelet_size=tubelet_size,
        resolution=resolution,
        dim_tokens=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=drop_rate,
        attn_drop_rate=attn_drop_rate,
        drop_path_rate=drop_path_rate,
        norm_layer=norm_layer,
        sincos_pos_emb=sincos_pos_emb,
        learnable_pos_emb=learnable_pos_emb,
        patch_proj=patch_proj,
        post_mlp=post_mlp,
        ckpt_path=ckpt_path,
    )
    return model

def vivit_l_enc(in_channels, 
              num_frames,
              tubelet_size, 
              resolution, 
              drop_rate=0.0,
              attn_drop_rate=0.0,
              drop_path_rate=0.0,
              norm_layer=partial(nn.LayerNorm, eps=1e-6),
              sincos_pos_emb=True,
              learnable_pos_emb=False,
              patch_proj=True,
              post_mlp=False):
    model = VivitEncoder(
        in_channels=in_channels, 
        num_frames=num_frames,
        tubelet_size=tubelet_size,
        resolution=resolution,
        dim_tokens=768, # 1024,
        depth=24,
        num_heads=16,
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=drop_rate,
        attn_drop_rate=attn_drop_rate,
        drop_path_rate=drop_path_rate,
        norm_layer=norm_layer,
        sincos_pos_emb=sincos_pos_emb,
        learnable_pos_emb=learnable_pos_emb,
        patch_proj=patch_proj,
        post_mlp=post_mlp,
    )
    return model


# Decoder presets

def vivit_s_dec(out_channels, 
              num_frames,
              tubelet_size, 
              resolution, 
              drop_rate=0.0,
              attn_drop_rate=0.0,
              drop_path_rate=0.0,
              norm_layer=partial(nn.LayerNorm, eps=1e-6),
              sincos_pos_emb=True,
              learnable_pos_emb=False,
              patch_proj=True,
              post_mlp=False,
              out_conv=False):
    model = VivitDecoder(
        out_channels=out_channels, 
        num_frames=num_frames,
        tubelet_size=tubelet_size,
        resolution=resolution,
        dim_tokens=512,
        depth=8,
        num_heads=8,
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=drop_rate,
        attn_drop_rate=attn_drop_rate,
        drop_path_rate=drop_path_rate,
        norm_layer=norm_layer,
        sincos_pos_emb=sincos_pos_emb,
        learnable_pos_emb=learnable_pos_emb,
        patch_proj=patch_proj,
        post_mlp=post_mlp,
        out_conv=out_conv,
    )
    return model

def vivit_b_dec(out_channels, 
              num_frames,
              tubelet_size, 
              resolution, 
              drop_rate=0.0,
              attn_drop_rate=0.0,
              drop_path_rate=0.0,
              norm_layer=partial(nn.LayerNorm, eps=1e-6),
              sincos_pos_emb=True,
              learnable_pos_emb=False,
              patch_proj=True,
              post_mlp=False,
              out_conv=False):
    model = VivitDecoder(
        out_channels=out_channels, 
        num_frames=num_frames,
        tubelet_size=tubelet_size,
        resolution=resolution,
        dim_tokens=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=drop_rate,
        attn_drop_rate=attn_drop_rate,
        drop_path_rate=drop_path_rate,
        norm_layer=norm_layer,
        sincos_pos_emb=sincos_pos_emb,
        learnable_pos_emb=learnable_pos_emb,
        patch_proj=patch_proj,
        post_mlp=post_mlp,
        out_conv=out_conv,
    )
    return model

def vivit_l_dec(out_channels, 
              num_frames,
              tubelet_size, 
              resolution, 
              drop_rate=0.0,
              attn_drop_rate=0.0,
              drop_path_rate=0.0,
              norm_layer=partial(nn.LayerNorm, eps=1e-6),
              sincos_pos_emb=True,
              learnable_pos_emb=False,
              patch_proj=True,
              post_mlp=False,
              out_conv=False):
    model = VivitDecoder(
        out_channels=out_channels, 
        num_frames=num_frames,
        tubelet_size=tubelet_size,
        resolution=resolution,
        dim_tokens=768, # 1024,
        depth=24,
        num_heads=16,
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=drop_rate,
        attn_drop_rate=attn_drop_rate,
        drop_path_rate=drop_path_rate,
        norm_layer=norm_layer,
        sincos_pos_emb=sincos_pos_emb,
        learnable_pos_emb=learnable_pos_emb,
        patch_proj=patch_proj,
        post_mlp=post_mlp,
        out_conv=out_conv,
    )
    return model


if __name__ == "__main__":
    x = torch.rand(2, 3, 32, 224, 224).cuda()
    vivit_enc = vivit_b_enc(in_channels=3, num_frames=32, tubelet_size=[2, 16, 16], resolution=224).cuda()
    x_enc = vivit_enc(x)
    print(x_enc.shape)

    vivit_dec = vivit_b_dec(out_channels=3, num_frames=32, tubelet_size=[2, 16, 16], resolution=224).cuda()
    x_dec = vivit_dec(x_enc)
    print(x_dec.shape)
